[template]
cargo_generate_version = "0.16.0"

[placeholders]
project-description = { type = "string", prompt = "Project Description" }
fast-compile = { type = "string", prompt = "Fast comple", choices = [
    "none",
    "dynamic",
    "lld",
], default = "dynamic" }

[conditional.'fast-compile != "lld"']
ignore = [".cargo"]

[hooks]
pre = ["ask-license.rhai"]
