[template]
cargo_generate_version = "0.17.3"

[placeholders]
project-description = { type = "string", prompt = "Project Description" }
dynamic-linking = { type = "bool", prompt = "Dynamic Linking", default = true }
linker = { type = "string", promt = "Linker", choices = [
"default",
"lld",
], default = "default" }

[conditional.'linker != "default"']
ignore = [".cargo"]

[hooks]
pre = ["ask-license.rhai"]
